# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aea7d7843f7ccc366a52284b12c2bcba248ccd2f0355c82fcdb2f3081c969b571bb2d15e1058125579c58166f6a91febb734a3b93865c7cd4527cdb06fa67e7a

test:
  secret_key_base: d59db8034825799560302ef1dbd03759876218b8b1102efeaf12317fcabf159a7a78e90c1a24f4a3098f6bd5dd6e95e6f5f6f29e1446f0f79e425c8553dac626

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
